labels:
  env: prod

ingress:
  traefik:
    enabled: true
    ingressClass: 'traefik'
    annotations: {}
    entryPoints: # possible values [web, websecure, admin]
    - websecure
    routeRules:
    - match: Host(`<%=projectNameHyphen%>.placer.team`)
      priority: 1000
      scheme: http
    tls:
      store:
        name: default

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "2000m"
    memory: "2048Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 40

dns:
  record:
    enabled: true
    lb_record: guru-prod-internal-l4-ingress.placer.team
    service_record_name: <%=projectNameHyphen%>.placer.team