{{- if .Values.dns.record.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-record"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns.record.service_record_name }}
    external-dns.alpha.kubernetes.io/ttl: "3600"
spec:
  type: ExternalName
  externalName: {{ .Values.dns.record.lb_record }}
{{- end }}