{{- if .Values.ingress.traefik.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "<%=projectNameHyphen%>.fullname" . }}-l5d-header-middleware
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "<%=projectNameHyphen%>.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: {{ include "<%=projectNameHyphen%>.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{.Values.service.externalPort}}
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "<%=projectNameHyphen%>.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "<%=projectNameHyphen%>.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ default "traefik" .Values.ingress.traefik.ingressClass }}
    {{- with .Values.ingress.traefik.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  entryPoints: {{ .Values.ingress.traefik.entryPoints }}
  routes:
  {{- $dot := . }}
  {{- range .Values.ingress.traefik.routeRules }}
  - kind: Rule  
    match: {{ .match }}
    priority: {{ default 0 .priority }}
    middlewares:
    - name: {{ include "<%=projectNameHyphen%>.fullname" $dot }}-l5d-header-middleware
    services:
    - kind: Service
      name: {{ template "<%=projectNameHyphen%>.fullname" $dot }}
      port: {{ $.Values.service.internalPort }}
      {{- if .scheme }}
      scheme: {{ .scheme }}
      {{- else }}
      scheme: {{ default "http" $.Values.service.protocol }} 
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.traefik.tls }}
  tls:
  {{- with .Values.ingress.traefik.tls }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}