{{- if .Values.secrets.enabled -}}
{{ $dot := .}}
{{- range .Values.secrets.secrets }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .name }}
  labels:
    {{- include "<%=projectNameHyphen%>.labels" $dot | nindent 4 }}
type: {{ .type }}
stringData:
  {{ .name }}: |-
{{ $.Files.Get .filePath  | indent 4 }}
{{- end }}
{{- end }}
