{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "<%=projectNameHyphen%>.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "<%=projectNameHyphen%>.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  #TODO: create a range port that can then be connected with various middlewares
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: {{ default "TCP" .Values.service.protocol }}
  selector:
    app.kubernetes.io/name: {{ template "<%=projectNameHyphen%>.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
