{{ $dot := . }}
{{- range .Values.configMaps.configs }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .name }}
  labels:
    {{- include "<%=projectNameHyphen%>.labels" $dot | nindent 4 }}
data:
  {{ .name }}: |-
{{ $.Files.Get .filePath  | indent 4 }}
{{- end }}
